### ISSUE TITLE
Problemas de instalación del entorno

### ISSUE THREAD

**Issue by carlospastormatut** [alastria/alastria-identity#9]
# Intalación del entorno según el documento Code Quality

## Resumen
Ha dado algún problema al hacer sudo npm install inicial
un warning al instalar solium
da error al hacer el ln
da error al instalar mythril

## Otros detalles:
Al principio del proceso he hecho npm install, pero lo he tenido que repetir al final para que me creara el node_modeules
Para usar solium hace falta hacer solium init

## Log completo
```
carlos@carlos-VirtualBox:~$ git clone https://github.com/alastria/alastria-identity -b feature/Registry
Cloning into 'alastria-identity'...
remote: Counting objects: 819, done.
remote: Compressing objects: 100% (176/176), done.
remote: Total 819 (delta 52), reused 219 (delta 45), pack-reused 576
Receiving objects: 100% (819/819), 15.44 MiB | 1.95 MiB/s, done.
Resolving deltas: 100% (379/379), done.
Checking connectivity... done.
carlos@carlos-VirtualBox:~$ cd alastria-identity/
carlos@carlos-VirtualBox:~/alastria-identity$ npm install 
npm WARN deprecated babel-preset-es2015@6.24.1: 🙌  Thanks for using Babel: we recommend using babel-preset-env now: please read babeljs.io/env to update! 
npm WARN deprecated ethereumjs-testrpc@3.9.2: ethereumjs-testrpc has been renamed to ganache-cli, please use this package from now on.
npm WARN deprecated npmconf@2.1.3: this package has been reintegrated into npm and is now out of date with respect to npm
npm WARN deprecated github@0.2.4: 'github' has been renamed to '@octokit/rest' (https://git.io/vNB11)
npm WARN deprecated @semantic-release/condition-travis@4.1.4: Use semantic-release@12.0.0 instead
npm WARN deprecated @semantic-release/last-release-npm@1.2.1: Use @semantic-release/npm instead
npm WARN deprecated conventional-changelog@0.0.17: Please update conventional-changelog to >1.0.0. If you are running the cli, use conventional-changelog-cli
npm WARN deprecated promise.prototype.finally@1.0.1: Please upgrade to v2.0 or higher!
npm WARN deprecated fs-promise@2.0.3: Use mz or fs-extra^3.0 with Promise Support
npm WARN deprecated tar.gz@1.0.7: ⚠️  WARNING ⚠️ tar.gz module has been deprecated and your application is vulnerable. Please use tar module instead: https://npmjs.com/tar
npm WARN deprecated graceful-fs@1.2.3: please upgrade to graceful-fs 4 for compatibility with current and future versions of Node.js
npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated nomnom@1.8.1: Package no longer supported. Contact support@npmjs.com for more info.
npm WARN deprecated formatio@1.1.1: This package is unmaintained. Use @sinonjs/formatio instead

> scrypt@6.0.3 preinstall /home/carlos/alastria-identity/node_modules/scrypt
> node node-scrypt-preinstall.js


> keccak@1.4.0 install /home/carlos/alastria-identity/node_modules/keccak
> npm run rebuild || echo "Keccak bindings compilation fail. Pure JS implementation will be used."


> keccak@1.4.0 rebuild /home/carlos/alastria-identity/node_modules/keccak
> node-gyp rebuild

make: Entering directory '/home/carlos/alastria-identity/node_modules/keccak/build'
  CXX(target) Release/obj.target/keccak/src/addon.o
  CC(target) Release/obj.target/keccak/src/libkeccak/KeccakSponge.o
  CC(target) Release/obj.target/keccak/src/libkeccak/KeccakP-1600-reference.o
  SOLINK_MODULE(target) Release/obj.target/keccak.node
  COPY Release/keccak.node
make: Leaving directory '/home/carlos/alastria-identity/node_modules/keccak/build'

> scrypt@6.0.3 install /home/carlos/alastria-identity/node_modules/scrypt
> node-gyp rebuild

make: Entering directory '/home/carlos/alastria-identity/node_modules/scrypt/build'
  SOLINK_MODULE(target) Release/obj.target/copied_files.node
  COPY Release/copied_files.node
  CC(target) Release/obj.target/scrypt_wrapper/src/util/memlimit.o
  CC(target) Release/obj.target/scrypt_wrapper/src/scryptwrapper/keyderivation.o
  CC(target) Release/obj.target/scrypt_wrapper/src/scryptwrapper/pickparams.o
  CC(target) Release/obj.target/scrypt_wrapper/src/scryptwrapper/hash.o
  AR(target) Release/obj.target/scrypt_wrapper.a
  COPY Release/scrypt_wrapper.a
  CC(target) Release/obj.target/scrypt_lib/scrypt/scrypt-1.2.0/lib/crypto/crypto_scrypt.o
  CC(target) Release/obj.target/scrypt_lib/scrypt/scrypt-1.2.0/lib/crypto/crypto_scrypt_smix.o
  CC(target) Release/obj.target/scrypt_lib/scrypt/scrypt-1.2.0/libcperciva/util/warnp.o
  CC(target) Release/obj.target/scrypt_lib/scrypt/scrypt-1.2.0/libcperciva/alg/sha256.o
  CC(target) Release/obj.target/scrypt_lib/scrypt/scrypt-1.2.0/libcperciva/util/insecure_memzero.o
  CC(target) Release/obj.target/scrypt_lib/scrypt/scrypt-1.2.0/lib/scryptenc/scryptenc_cpuperf.o
  AR(target) Release/obj.target/scrypt_lib.a
  COPY Release/scrypt_lib.a
  CXX(target) Release/obj.target/scrypt/src/node-boilerplate/scrypt_common.o
  CXX(target) Release/obj.target/scrypt/src/node-boilerplate/scrypt_params_async.o
In file included from ../src/node-boilerplate/inc/scrypt_params_async.h:28:0,
                 from ../src/node-boilerplate/scrypt_params_async.cc:4:
../src/node-boilerplate/inc/scrypt_async.h: In member function ‘virtual void ScryptAsyncWorker::HandleErrorCallback()’:
../src/node-boilerplate/inc/scrypt_async.h:53:29: warning: ‘v8::Local<v8::Value> Nan::Callback::Call(int, v8::Local<v8::Value>*) const’ is deprecated [-Wdeprecated-declarations]
       callback->Call(1, argv);
                             ^
In file included from ../src/node-boilerplate/scrypt_params_async.cc:1:0:
../../nan/nan.h:1618:3: note: declared here
   Call(int argc, v8::Local<v8::Value> argv[]) const {
   ^
../src/node-boilerplate/scrypt_params_async.cc: In member function ‘virtual void ScryptParamsAsyncWorker::HandleOKCallback()’:
../src/node-boilerplate/scrypt_params_async.cc:32:25: warning: ‘v8::Local<v8::Value> Nan::Callback::Call(int, v8::Local<v8::Value>*) const’ is deprecated [-Wdeprecated-declarations]
   callback->Call(2, argv);
                         ^
In file included from ../src/node-boilerplate/scrypt_params_async.cc:1:0:
../../nan/nan.h:1618:3: note: declared here
   Call(int argc, v8::Local<v8::Value> argv[]) const {
   ^
  CXX(target) Release/obj.target/scrypt/src/node-boilerplate/scrypt_params_sync.o
  CXX(target) Release/obj.target/scrypt/src/node-boilerplate/scrypt_kdf_async.o
In file included from ../src/node-boilerplate/inc/scrypt_kdf_async.h:28:0,
                 from ../src/node-boilerplate/scrypt_kdf_async.cc:4:
../src/node-boilerplate/inc/scrypt_async.h: In member function ‘virtual void ScryptAsyncWorker::HandleErrorCallback()’:
../src/node-boilerplate/inc/scrypt_async.h:53:29: warning: ‘v8::Local<v8::Value> Nan::Callback::Call(int, v8::Local<v8::Value>*) const’ is deprecated [-Wdeprecated-declarations]
       callback->Call(1, argv);
                             ^
In file included from ../src/node-boilerplate/scrypt_kdf_async.cc:1:0:
../../nan/nan.h:1618:3: note: declared here
   Call(int argc, v8::Local<v8::Value> argv[]) const {
   ^
../src/node-boilerplate/scrypt_kdf_async.cc: In member function ‘virtual void ScryptKDFAsyncWorker::HandleOKCallback()’:
../src/node-boilerplate/scrypt_kdf_async.cc:28:27: warning: ‘v8::Local<v8::Value> Nan::Callback::Call(int, v8::Local<v8::Value>*) const’ is deprecated [-Wdeprecated-declarations]
     callback->Call(2, argv);
                           ^
In file included from ../src/node-boilerplate/scrypt_kdf_async.cc:1:0:
../../nan/nan.h:1618:3: note: declared here
   Call(int argc, v8::Local<v8::Value> argv[]) const {
   ^
  CXX(target) Release/obj.target/scrypt/src/node-boilerplate/scrypt_kdf_sync.o
  CXX(target) Release/obj.target/scrypt/src/node-boilerplate/scrypt_kdf-verify_sync.o
  CXX(target) Release/obj.target/scrypt/src/node-boilerplate/scrypt_kdf-verify_async.o
In file included from ../src/node-boilerplate/inc/scrypt_kdf-verify_async.h:28:0,
                 from ../src/node-boilerplate/scrypt_kdf-verify_async.cc:4:
../src/node-boilerplate/inc/scrypt_async.h: In member function ‘virtual void ScryptAsyncWorker::HandleErrorCallback()’:
../src/node-boilerplate/inc/scrypt_async.h:53:29: warning: ‘v8::Local<v8::Value> Nan::Callback::Call(int, v8::Local<v8::Value>*) const’ is deprecated [-Wdeprecated-declarations]
       callback->Call(1, argv);
                             ^
In file included from ../src/node-boilerplate/scrypt_kdf-verify_async.cc:1:0:
../../nan/nan.h:1618:3: note: declared here
   Call(int argc, v8::Local<v8::Value> argv[]) const {
   ^
../src/node-boilerplate/scrypt_kdf-verify_async.cc: In member function ‘virtual void ScryptKDFVerifyAsyncWorker::HandleOKCallback()’:
../src/node-boilerplate/scrypt_kdf-verify_async.cc:30:25: warning: ‘v8::Local<v8::Value> Nan::Callback::Call(int, v8::Local<v8::Value>*) const’ is deprecated [-Wdeprecated-declarations]
   callback->Call(2, argv);
                         ^
In file included from ../src/node-boilerplate/scrypt_kdf-verify_async.cc:1:0:
../../nan/nan.h:1618:3: note: declared here
   Call(int argc, v8::Local<v8::Value> argv[]) const {
   ^
  CXX(target) Release/obj.target/scrypt/src/node-boilerplate/scrypt_hash_sync.o
  CXX(target) Release/obj.target/scrypt/src/node-boilerplate/scrypt_hash_async.o
In file included from ../src/node-boilerplate/inc/scrypt_hash_async.h:28:0,
                 from ../src/node-boilerplate/scrypt_hash_async.cc:28:
../src/node-boilerplate/inc/scrypt_async.h: In member function ‘virtual void ScryptAsyncWorker::HandleErrorCallback()’:
../src/node-boilerplate/inc/scrypt_async.h:53:29: warning: ‘v8::Local<v8::Value> Nan::Callback::Call(int, v8::Local<v8::Value>*) const’ is deprecated [-Wdeprecated-declarations]
       callback->Call(1, argv);
                             ^
In file included from ../src/node-boilerplate/scrypt_hash_async.cc:25:0:
../../nan/nan.h:1618:3: note: declared here
   Call(int argc, v8::Local<v8::Value> argv[]) const {
   ^
../src/node-boilerplate/scrypt_hash_async.cc: In member function ‘virtual void ScryptHashAsyncWorker::HandleOKCallback()’:
../src/node-boilerplate/scrypt_hash_async.cc:52:25: warning: ‘v8::Local<v8::Value> Nan::Callback::Call(int, v8::Local<v8::Value>*) const’ is deprecated [-Wdeprecated-declarations]
   callback->Call(2, argv);
                         ^
In file included from ../src/node-boilerplate/scrypt_hash_async.cc:25:0:
../../nan/nan.h:1618:3: note: declared here
   Call(int argc, v8::Local<v8::Value> argv[]) const {
   ^
  CXX(target) Release/obj.target/scrypt/scrypt_node.o
  SOLINK_MODULE(target) Release/obj.target/scrypt.node
  COPY Release/scrypt.node
make: Leaving directory '/home/carlos/alastria-identity/node_modules/scrypt/build'

> secp256k1@3.5.0 install /home/carlos/alastria-identity/node_modules/secp256k1
> npm run rebuild || echo "Secp256k1 bindings compilation fail. Pure JS implementation will be used."


> secp256k1@3.5.0 rebuild /home/carlos/alastria-identity/node_modules/secp256k1
> node-gyp rebuild

make: Entering directory '/home/carlos/alastria-identity/node_modules/secp256k1/build'
  CXX(target) Release/obj.target/secp256k1/src/addon.o
  CXX(target) Release/obj.target/secp256k1/src/privatekey.o
../src/privatekey.cc: In function ‘Nan::NAN_METHOD_RETURN_TYPE privateKeyNegate(Nan::NAN_METHOD_ARGS_TYPE)’:
../src/privatekey.cc:73:61: warning: ignoring return value of ‘int secp256k1_ec_privkey_negate(const secp256k1_context*, unsigned char*)’, declared with attribute warn_unused_result [-Wunused-result]
   secp256k1_ec_privkey_negate(secp256k1ctx, &private_key[0]);
                                                             ^
  CXX(target) Release/obj.target/secp256k1/src/publickey.o
  CXX(target) Release/obj.target/secp256k1/src/signature.o
  CXX(target) Release/obj.target/secp256k1/src/ecdsa.o
  CXX(target) Release/obj.target/secp256k1/src/ecdh.o
  CC(target) Release/obj.target/secp256k1/src/secp256k1-src/src/secp256k1.o
  CC(target) Release/obj.target/secp256k1/src/secp256k1-src/contrib/lax_der_parsing.o
  CC(target) Release/obj.target/secp256k1/src/secp256k1-src/contrib/lax_der_privatekey_parsing.o
  SOLINK_MODULE(target) Release/obj.target/secp256k1.node
  COPY Release/secp256k1.node
make: Leaving directory '/home/carlos/alastria-identity/node_modules/secp256k1/build'

> sha3@1.2.2 install /home/carlos/alastria-identity/node_modules/sha3
> node-gyp rebuild

make: Entering directory '/home/carlos/alastria-identity/node_modules/sha3/build'
  CXX(target) Release/obj.target/sha3/src/addon.o
  CXX(target) Release/obj.target/sha3/src/displayIntermediateValues.o
  CXX(target) Release/obj.target/sha3/src/KeccakF-1600-reference.o
  CXX(target) Release/obj.target/sha3/src/KeccakNISTInterface.o
  CXX(target) Release/obj.target/sha3/src/KeccakSponge.o
  SOLINK_MODULE(target) Release/obj.target/sha3.node
  COPY Release/sha3.node
make: Leaving directory '/home/carlos/alastria-identity/node_modules/sha3/build'

> execSync@1.0.2 install /home/carlos/alastria-identity/node_modules/execSync
> node install.js

[execsync v1.0.2] Attempting to compile native extensions.
[execSync v1.0.2]
    Native code compile failed!!

> phantomjs-prebuilt@2.1.16 install /home/carlos/alastria-identity/node_modules/phantomjs-prebuilt
> node install.js

PhantomJS not found on PATH
Downloading https://github.com/Medium/phantomjs/releases/download/v2.1.1/phantomjs-2.1.1-linux-x86_64.tar.bz2
Saving to /tmp/phantomjs/phantomjs-2.1.1-linux-x86_64.tar.bz2
Receiving...

Error making request.
Error: self signed certificate in certificate chain
    at TLSSocket.<anonymous> (_tls_wrap.js:1098:38)
    at emitNone (events.js:105:13)
    at TLSSocket.emit (events.js:207:7)
    at TLSSocket._finishInit (_tls_wrap.js:628:8)
    at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:458:38)

Please report this full log at https://github.com/Medium/phantomjs
npm WARN webpack-cli@2.1.5 requires a peer of webpack@^4.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN The package json-loader is included as both a dev and production dependency.
npm WARN The package web3 is included as both a dev and production dependency.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.4 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.4: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! phantomjs-prebuilt@2.1.16 install: `node install.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the phantomjs-prebuilt@2.1.16 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/carlos/.npm/_logs/2018-07-16T16_19_48_600Z-debug.log
carlos@carlos-VirtualBox:~/alastria-identity$ sudo node npm
[sudo] password for carlos: 
module.js:549
    throw err;
    ^

Error: Cannot find module '/home/carlos/alastria-identity/npm'
    at Function.Module._resolveFilename (module.js:547:15)
    at Function.Module._load (module.js:474:25)
    at Function.Module.runMain (module.js:693:10)
    at startup (bootstrap_node.js:191:16)
    at bootstrap_node.js:612:3
carlos@carlos-VirtualBox:~/alastria-identity$ sudo npm install
npm ERR! code 1
npm ERR! Command failed: /usr/bin/git clone -q https://github.com/frozeman/bignumber.js-nolookahead.git /home/carlos/.npm/_cacache/tmp/git-clone-3b8e2e2c
npm ERR! /home/carlos/.npm/_cacache/tmp/git-clone-3b8e2e2c/.git: Permission denied
npm ERR! 

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/carlos/.npm/_logs/2018-07-16T16_21_08_111Z-debug.log
carlos@carlos-VirtualBox:~/alastria-identity$ cd ..
carlos@carlos-VirtualBox:~$ rm -rf alastria-identity/
carlos@carlos-VirtualBox:~$ history 
    1  git clone https://github.com/alastria/alastria-identity -b feature/Registry
    2  cd alastria-identity/
    3  npm install 
    4  sudo node npm
    5  sudo npm install
    6  cd ..
    7  rm -rf alastria-identity/
    8  history 
carlos@carlos-VirtualBox:~$ history -c 
carlos@carlos-VirtualBox:~$ git clone https://github.com/alastria/alastria-identity -b feature/Registry
Cloning into 'alastria-identity'...
remote: Counting objects: 819, done.
remote: Compressing objects: 100% (176/176), done.
remote: Total 819 (delta 52), reused 219 (delta 45), pack-reused 576
Receiving objects: 100% (819/819), 15.44 MiB | 444.00 KiB/s, done.
Resolving deltas: 100% (379/379), done.
Checking connectivity... done.
carlos@carlos-VirtualBox:~$ cd alastria-identity/
carlos@carlos-VirtualBox:~/alastria-identity$ sudo npm install
npm WARN deprecated babel-preset-es2015@6.24.1: 🙌  Thanks for using Babel: we recommend using babel-preset-env now: please read babeljs.io/env to update! 
npm WARN deprecated ethereumjs-testrpc@3.9.2: ethereumjs-testrpc has been renamed to ganache-cli, please use this package from now on.
npm WARN deprecated @semantic-release/condition-travis@4.1.4: Use semantic-release@12.0.0 instead
npm WARN deprecated @semantic-release/last-release-npm@1.2.1: Use @semantic-release/npm instead
npm WARN deprecated github@0.2.4: 'github' has been renamed to '@octokit/rest' (https://git.io/vNB11)
npm WARN deprecated npmconf@2.1.3: this package has been reintegrated into npm and is now out of date with respect to npm
npm WARN deprecated conventional-changelog@0.0.17: Please update conventional-changelog to >1.0.0. If you are running the cli, use conventional-changelog-cli
npm WARN deprecated promise.prototype.finally@1.0.1: Please upgrade to v2.0 or higher!
npm WARN deprecated fs-promise@2.0.3: Use mz or fs-extra^3.0 with Promise Support
npm WARN deprecated tar.gz@1.0.7: ⚠️  WARNING ⚠️ tar.gz module has been deprecated and your application is vulnerable. Please use tar module instead: https://npmjs.com/tar
npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated graceful-fs@1.2.3: please upgrade to graceful-fs 4 for compatibility with current and future versions of Node.js
npm WARN deprecated nomnom@1.8.1: Package no longer supported. Contact support@npmjs.com for more info.
npm ERR! code 1
npm ERR! Command failed: /usr/bin/git clone -q https://github.com/frozeman/bignumber.js-nolookahead.git /home/carlos/.npm/_cacache/tmp/git-clone-e9a0ab6f
npm ERR! /home/carlos/.npm/_cacache/tmp/git-clone-e9a0ab6f/.git: Permission denied
npm ERR! 

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/carlos/.npm/_logs/2018-07-16T16_23_14_924Z-debug.log
carlos@carlos-VirtualBox:~/alastria-identity$ sudo npm install -g truffle
/usr/bin/truffle -> /usr/lib/node_modules/truffle/build/cli.bundled.js
+ truffle@4.1.13
updated 1 package in 3.856s
carlos@carlos-VirtualBox:~/alastria-identity$ sudo npm install -g ganache-cli
/usr/bin/ganache-cli -> /usr/lib/node_modules/ganache-cli/build/cli.node.js
+ ganache-cli@6.1.6
updated 1 package in 2.411s
carlos@carlos-VirtualBox:~/alastria-identity$ sudo npm install -g solium
/usr/bin/solium -> /usr/lib/node_modules/solium/bin/solium.js
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.4 (node_modules/solium/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.4: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

+ solium@1.1.8
updated 1 package in 7.865s
carlos@carlos-VirtualBox:~/alastria-identity$ sudo apt-get update
Hit:1 http://ppa.launchpad.net/ethereum/ethereum-dev/ubuntu xenial InRelease
Hit:2 http://es.archive.ubuntu.com/ubuntu xenial InRelease                                     
Get:3 http://security.ubuntu.com/ubuntu xenial-security InRelease [107 kB]                     
Get:4 http://es.archive.ubuntu.com/ubuntu xenial-updates InRelease [109 kB]                                             
Hit:5 https://deb.nodesource.com/node_8.x xenial InRelease                                                              
Hit:6 http://ppa.launchpad.net/ethereum/ethereum/ubuntu xenial InRelease                                             
Hit:7 http://ppa.launchpad.net/mamantoha/gti/ubuntu xenial InRelease                                                    
Get:8 http://es.archive.ubuntu.com/ubuntu xenial-backports InRelease [107 kB]                             
Hit:9 http://ppa.launchpad.net/webupd8team/atom/ubuntu xenial InRelease                                        
Get:10 http://es.archive.ubuntu.com/ubuntu xenial-updates/main amd64 DEP-11 Metadata [318 kB]
Get:11 http://security.ubuntu.com/ubuntu xenial-security/main amd64 DEP-11 Metadata [67,7 kB]            
Get:12 http://es.archive.ubuntu.com/ubuntu xenial-updates/main DEP-11 64x64 Icons [238 kB]                              
Get:13 http://security.ubuntu.com/ubuntu xenial-security/main DEP-11 64x64 Icons [72,6 kB]                             
Get:14 http://es.archive.ubuntu.com/ubuntu xenial-updates/universe amd64 DEP-11 Metadata [246 kB]                       
Get:15 http://es.archive.ubuntu.com/ubuntu xenial-updates/universe DEP-11 64x64 Icons [331 kB]                          
Get:16 http://es.archive.ubuntu.com/ubuntu xenial-updates/multiverse amd64 DEP-11 Metadata [5.964 B]                    
Get:17 http://security.ubuntu.com/ubuntu xenial-security/universe amd64 DEP-11 Metadata [107 kB]                        
Get:18 http://security.ubuntu.com/ubuntu xenial-security/universe DEP-11 64x64 Icons [147 kB]         
Get:19 http://es.archive.ubuntu.com/ubuntu xenial-backports/main amd64 DEP-11 Metadata [3.328 B]
Get:20 http://es.archive.ubuntu.com/ubuntu xenial-backports/universe amd64 DEP-11 Metadata [5.100 B]
Fetched 1.864 kB in 2s (916 kB/s)                                             
AppStream cache update completed, but some metadata was ignored due to errors.
Reading package lists... Done
carlos@carlos-VirtualBox:~/alastria-identity$ sudo apt-get install -y software-properties-common
Reading package lists... Done
Building dependency tree       
Reading state information... Done
software-properties-common is already the newest version (0.96.20.7).
The following packages were automatically installed and are no longer required:
  libllvm4.0 libqt4-opengl linux-headers-4.10.0-28 linux-headers-4.10.0-28-generic linux-headers-4.13.0-31
  linux-headers-4.13.0-31-generic linux-headers-4.13.0-32 linux-headers-4.13.0-32-generic linux-headers-4.13.0-36
  linux-headers-4.13.0-36-generic linux-headers-4.13.0-39 linux-headers-4.13.0-39-generic linux-headers-4.13.0-41
  linux-headers-4.13.0-41-generic linux-headers-4.13.0-43 linux-headers-4.13.0-43-generic linux-image-4.10.0-28-generic
  linux-image-4.13.0-31-generic linux-image-4.13.0-32-generic linux-image-4.13.0-36-generic
  linux-image-4.13.0-39-generic linux-image-4.13.0-41-generic linux-image-4.13.0-43-generic
  linux-image-extra-4.10.0-28-generic linux-image-extra-4.13.0-31-generic linux-image-extra-4.13.0-32-generic
  linux-image-extra-4.13.0-36-generic linux-image-extra-4.13.0-39-generic linux-image-extra-4.13.0-41-generic
  linux-image-extra-4.13.0-43-generic
Use 'sudo apt autoremove' to remove them.
0 upgraded, 0 newly installed, 0 to remove and 45 not upgraded.
carlos@carlos-VirtualBox:~/alastria-identity$ sudo add-apt-repository -y ppa:ethereum/ethereum
gpg: keyring `/tmp/tmprm2y4f5r/secring.gpg' created
gpg: keyring `/tmp/tmprm2y4f5r/pubring.gpg' created
gpg: requesting key 923F6CA9 from hkp server keyserver.ubuntu.com
gpg: /tmp/tmprm2y4f5r/trustdb.gpg: trustdb created
gpg: key 923F6CA9: public key "Launchpad PPA for Ethereum" imported
gpg: Total number processed: 1
gpg:               imported: 1  (RSA: 1)
OK
carlos@carlos-VirtualBox:~/alastria-identity$ sudo apt-get update
Hit:1 http://ppa.launchpad.net/ethereum/ethereum-dev/ubuntu xenial InRelease
Hit:2 http://security.ubuntu.com/ubuntu xenial-security InRelease                                                       
Hit:3 http://es.archive.ubuntu.com/ubuntu xenial InRelease                                                              
Hit:4 http://ppa.launchpad.net/ethereum/ethereum/ubuntu xenial InRelease 
Hit:5 http://es.archive.ubuntu.com/ubuntu xenial-updates InRelease                                  
Hit:6 http://es.archive.ubuntu.com/ubuntu xenial-backports InRelease                                
Hit:7 http://ppa.launchpad.net/mamantoha/gti/ubuntu xenial InRelease                                
Hit:8 http://ppa.launchpad.net/webupd8team/atom/ubuntu xenial InRelease       
Hit:9 https://deb.nodesource.com/node_8.x xenial InRelease
Reading package lists... Done
carlos@carlos-VirtualBox:~/alastria-identity$ sudo apt-get install -y solc
Reading package lists... Done
Building dependency tree       
Reading state information... Done
solc is already the newest version (1:0.4.25-develop-2018-06-21-32f2db78-0ubuntu1~xenial).
The following packages were automatically installed and are no longer required:
  libllvm4.0 libqt4-opengl linux-headers-4.10.0-28 linux-headers-4.10.0-28-generic linux-headers-4.13.0-31
  linux-headers-4.13.0-31-generic linux-headers-4.13.0-32 linux-headers-4.13.0-32-generic linux-headers-4.13.0-36
  linux-headers-4.13.0-36-generic linux-headers-4.13.0-39 linux-headers-4.13.0-39-generic linux-headers-4.13.0-41
  linux-headers-4.13.0-41-generic linux-headers-4.13.0-43 linux-headers-4.13.0-43-generic linux-image-4.10.0-28-generic
  linux-image-4.13.0-31-generic linux-image-4.13.0-32-generic linux-image-4.13.0-36-generic
  linux-image-4.13.0-39-generic linux-image-4.13.0-41-generic linux-image-4.13.0-43-generic
  linux-image-extra-4.10.0-28-generic linux-image-extra-4.13.0-31-generic linux-image-extra-4.13.0-32-generic
  linux-image-extra-4.13.0-36-generic linux-image-extra-4.13.0-39-generic linux-image-extra-4.13.0-41-generic
  linux-image-extra-4.13.0-43-generic
Use 'sudo apt autoremove' to remove them.
0 upgraded, 0 newly installed, 0 to remove and 45 not upgraded.
carlos@carlos-VirtualBox:~/alastria-identity$ sudo apt-get install libssl-dev
Reading package lists... Done
Building dependency tree       
Reading state information... Done
libssl-dev is already the newest version (1.0.2g-1ubuntu4.13).
The following packages were automatically installed and are no longer required:
  libllvm4.0 libqt4-opengl linux-headers-4.10.0-28 linux-headers-4.10.0-28-generic linux-headers-4.13.0-31
  linux-headers-4.13.0-31-generic linux-headers-4.13.0-32 linux-headers-4.13.0-32-generic linux-headers-4.13.0-36
  linux-headers-4.13.0-36-generic linux-headers-4.13.0-39 linux-headers-4.13.0-39-generic linux-headers-4.13.0-41
  linux-headers-4.13.0-41-generic linux-headers-4.13.0-43 linux-headers-4.13.0-43-generic linux-image-4.10.0-28-generic
  linux-image-4.13.0-31-generic linux-image-4.13.0-32-generic linux-image-4.13.0-36-generic
  linux-image-4.13.0-39-generic linux-image-4.13.0-41-generic linux-image-4.13.0-43-generic
  linux-image-extra-4.10.0-28-generic linux-image-extra-4.13.0-31-generic linux-image-extra-4.13.0-32-generic
  linux-image-extra-4.13.0-36-generic linux-image-extra-4.13.0-39-generic linux-image-extra-4.13.0-41-generic
  linux-image-extra-4.13.0-43-generic
Use 'sudo apt autoremove' to remove them.
0 upgraded, 0 newly installed, 0 to remove and 45 not upgraded.
carlos@carlos-VirtualBox:~/alastria-identity$ sudo apt-get install -y python3-pip=9.0.1-2 python3-dev
Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Version '9.0.1-2' for 'python3-pip' was not found
carlos@carlos-VirtualBox:~/alastria-identity$ sudo ln -s /usr/bin/python3 /usr/local/bin/python
ln: failed to create symbolic link '/usr/local/bin/python': File exists
carlos@carlos-VirtualBox:~/alastria-identity$ sudo apt-get install -y pandoc
Reading package lists... Done
Building dependency tree       
Reading state information... Done
pandoc is already the newest version (1.16.0.2~dfsg-1).
The following packages were automatically installed and are no longer required:
  libllvm4.0 libqt4-opengl linux-headers-4.10.0-28 linux-headers-4.10.0-28-generic linux-headers-4.13.0-31
  linux-headers-4.13.0-31-generic linux-headers-4.13.0-32 linux-headers-4.13.0-32-generic linux-headers-4.13.0-36
  linux-headers-4.13.0-36-generic linux-headers-4.13.0-39 linux-headers-4.13.0-39-generic linux-headers-4.13.0-41
  linux-headers-4.13.0-41-generic linux-headers-4.13.0-43 linux-headers-4.13.0-43-generic linux-image-4.10.0-28-generic
  linux-image-4.13.0-31-generic linux-image-4.13.0-32-generic linux-image-4.13.0-36-generic
  linux-image-4.13.0-39-generic linux-image-4.13.0-41-generic linux-image-4.13.0-43-generic
  linux-image-extra-4.10.0-28-generic linux-image-extra-4.13.0-31-generic linux-image-extra-4.13.0-32-generic
  linux-image-extra-4.13.0-36-generic linux-image-extra-4.13.0-39-generic linux-image-extra-4.13.0-41-generic
  linux-image-extra-4.13.0-43-generic
Use 'sudo apt autoremove' to remove them.
0 upgraded, 0 newly installed, 0 to remove and 45 not upgraded.
carlos@carlos-VirtualBox:~/alastria-identity$ sudo apt-get install -y git
Reading package lists... Done
Building dependency tree       
Reading state information... Done
git is already the newest version (1:2.7.4-0ubuntu1.4).
The following packages were automatically installed and are no longer required:
  libllvm4.0 libqt4-opengl linux-headers-4.10.0-28 linux-headers-4.10.0-28-generic linux-headers-4.13.0-31
  linux-headers-4.13.0-31-generic linux-headers-4.13.0-32 linux-headers-4.13.0-32-generic linux-headers-4.13.0-36
  linux-headers-4.13.0-36-generic linux-headers-4.13.0-39 linux-headers-4.13.0-39-generic linux-headers-4.13.0-41
  linux-headers-4.13.0-41-generic linux-headers-4.13.0-43 linux-headers-4.13.0-43-generic linux-image-4.10.0-28-generic
  linux-image-4.13.0-31-generic linux-image-4.13.0-32-generic linux-image-4.13.0-36-generic
  linux-image-4.13.0-39-generic linux-image-4.13.0-41-generic linux-image-4.13.0-43-generic
  linux-image-extra-4.10.0-28-generic linux-image-extra-4.13.0-31-generic linux-image-extra-4.13.0-32-generic
  linux-image-extra-4.13.0-36-generic linux-image-extra-4.13.0-39-generic linux-image-extra-4.13.0-41-generic
  linux-image-extra-4.13.0-43-generic
Use 'sudo apt autoremove' to remove them.
0 upgraded, 0 newly installed, 0 to remove and 45 not upgraded.
carlos@carlos-VirtualBox:~/alastria-identity$ pip3 install mythril
Traceback (most recent call last):
  File "/usr/bin/pip3", line 9, in <module>
    from pip import main
ImportError: cannot import name 'main'
carlos@carlos-VirtualBox:~/alastria-identity$ 
```

**Comment by marcosio** [comment]
Carlos:

1. `npm install` must be used without `sudo`. 
2. Try to correct the `pip3` installation with this article `https://stackoverflow.com/questions/49836676/error-after-upgrading-pip-cannot-import-name-main`.

**Comment by msalitu** [comment]
I had the same issue as Carlos. It worked with this command:
`sudo apt install python3-pip`
Maybe it helps.
